name: CI with Cache

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-130dbb1

      - name: prime-cache-130dbb1
        run: echo "Cache hit? ${{ steps.cache-deps.outputs.cache-hit }}"

      - name: Install deps
        run: pip install -r requirements.txt
